<html>
    <head>
        <link rel="stylesheet" href="css/user.css" type="text/css">
    </head>
    <body>
        <div id="heading">Users</div>
        <ul id='users'>
            <li class="user">
                <input class="forename" value="Ramanathan">
                <input class="surname" value="Balakrishnan">

                <div class="action"></div>
            </li>
            <li class="user empty">
                <input class="forename" value="Forename">
                <input class="surname" value="Surname">

                <div class="action"></div>
            </li>
            <li class="user empty">
                <input class="forename" value="Forename">
                <input class="surname" value="Surname">

                <div class="action"></div>
            </li>
            <li class="user empty">
                <input class="forename" value="Forename">
                <input class="surname" value="Surname">

                <div class="action"></div>
            </li>
            <li class="user empty">
                <input class="forename" value="Forename">
                <input class="surname" value="Surname">

                <div class="action"></div>
            </li>
        </ul>
        <div class="add-user"><input type="button" value="Add more"></div>
    </body>
</html>